### ISSUE TITLE
Proper usage of version control

### ISSUE THREAD

**Issue by m007** [threema-ch/threema-msgapi-sdk-java#4]
# Problem
No file which can be *generated from the code* should be added to version control. See [here](http://perlmaven.com/dont-keep-generated-files-in-version-control).

# How to find out
... I think this should not needed to be explained to a software developer.

# How to fix
Remove the ```.jar``` file from version control (git). Maybe add text explaining how to generate it in the ```Readme``` (see #3).

**Comment by micwin** [comment]
I'm about to configure maven central upload in your pom file. If you gimme a day or so I'll fix that for you ;)

**Comment by micwin** [comment]
See my pull request #6. You still have to do some parts but if done, you simply can link to maven central binaries like on my ticino page: <http://micwin.github.io/ticino> (scroll to the bottom where I directly link the jars). Since the site is generated with maven site, I use filtering to insert the proper ${project.version} so the link automatically adjusts when releasing new stuff.

the source of this page is here (<https://github.com/micwin/ticino/blob/master/site/src/site/apt/index.apt.vm>), the resource filtering tricks happen on lines 45, 48 and 51

I didnt use mardowwn, though, but should be easy to adjust if put into src/site/markdown.

grx mic

**Comment by micwin** [comment]
Some idea when the threema java sdk goes maven central?

**Comment by threema-ch** [comment]
Sorry for the late reply. Maven central deployment is currently not planned,
